### ISSUE TITLE
Use of Registry ontology is incorrect

### ISSUE THREAD

**Issue by dr-shorthair** [GeoscienceAustralia/Place-Names#10]
The documentation in the [Registry Ontology](http://purl.org/linked-data/registry) is clear that 
- `reg:Registry` is a _metadata_ registry 
- `reg:RegistryItem` is a _metadata record_ rather than an Entity - Entity is still two edges away in a graph

Need to disentangle Placenames ontology from Registry ontology so that:

1. `pn:Gazetteer` is not a sub-class of `reg:Registry`
2. `pn:PlaceName` is not a sub-class of `reg:RegistryItem`
3. `pn:register` is not a sub-property of `reg:registry`

**Comment by bellie888** [comment]
The live instance on AWS:
http://ec2-52-63-73-113.ap-southeast-2.compute.amazonaws.com/placenames-dataset/

is  the placenames-dataset API Git repo – connected to the placenames database
on Git it is called GeoscienceAustralia/placenames-dataset

I see you are working in the ontology Git Repo called just ‘GeoscienceAustralia/Place-Names’ which is OK but is not the source for the AWS instance.

Is that right, or am I confused :)

**Comment by bellie888** [comment]
Thanks Simon, I'll use your excellent examples to change the python code so that the alternate views on AWS are the same. Just what I needed, cause I only have a basic understanding in this area.
