### ISSUE TITLE
Is a Gazetteer a list of places, or place-names?

### ISSUE THREAD

**Issue by dr-shorthair** [GeoscienceAustralia/Place-Names#12]
In the [Place Name ontology](http://www.linked.data.gov.au/def/placenames/), `Place` (a sub-class of `geo:Feature` with a type and geometry) is differentiated from `PlaceName` (a formal name for the place, assigned by some authority). 

So what is the membership of a Gazetteer? is it Place or PlaceName?

**Comment by bellie888** [comment]
Irina and I think they are placenames, not places. The dataset has uri links to all the data sources, so you can check the various 'jurisdictions' to see what the data looks like. This puts a tension between a 'feature' and the names of that feature - as I see it. One feature can have many names (although there is generally just one 'official name' in our dataset. We have only one name for each 'placename'.

**Comment by ibastrak** [comment]
According to the documentation (https://s3-ap-southeast-2.amazonaws.com/fsdf.placenames/DPS/Composite+Gazetteer+DPS.pdf) this is:
The purpose of this document is to specify a harmonised data specification for official place
names. It specifies the format, content, and characteristic detail necessary to combine
jurisdictional data for the production of a place names database. This specification also
provides a guideline for the preparation and use of place name information.
The thematic scope of this data specification is towards providing a framework for naming of
features.

**Comment by dr-shorthair** [comment]
Reopening until I fixed the ontology

**Comment by dr-shorthair** [comment]
fixed by #9
