### ISSUE TITLE
What to align with - PROV, schema.org (, Org)

### ISSUE THREAD

**Issue by dr-shorthair** [GeoscienceAustralia/Place-Names#13]
The ontology is partly aligned with PROV-O (prov:Agent, prov:isAttributedTo, ...) and partly with schema.org (schema.Organization). Best if the model is consistent. Will align with PROV-O for now. 

(Ontology metadata is another matter - this might use schema.org elements.)

**Comment by bellie888** [comment]
OK - relying on your experience and knowledge. 
I have been editing the API to output your examples properly.

**Comment by ibastrak** [comment]
I agree with Simon on Prov-O

**Comment by dr-shorthair** [comment]
Thanks @bellie888 - as you can see I'm trying to tidy up the ontology while I'm working through this example. 

When you say 'editing the API' what RDF library are you using? 
(I'm a bit concerned that the original chimera indicates that you are rolling your own ...)

**Comment by dr-shorthair** [comment]
fixed by #9

**Comment by bellie888** [comment]
@dr-shorthair Hi Simon,
Using these:
from pyldapi import Renderer, View
from rdflib import Graph, URIRef, RDF, XSD, Namespace, Literal
standard ones that Nick Carr set us up with   -no roll your own.
Cheers
