### ISSUE TITLE
hasPlaceNamingAuthority vs wasNamedBy

### ISSUE THREAD

**Issue by dr-shorthair** [GeoscienceAustralia/Place-Names#14]
What is the practical difference between these two properties?

**Comment by ibastrak** [comment]
The Place Naming Authority has official status and role in registering the name of a place. It is represented by an organisation such as AAD or Jurisdictional Government Organisation. At the same time, the name can be defined by an individual or a group of people.

**Comment by dr-shorthair** [comment]
So is `hasPlaceNamingAuthority` a special case of `wasNamedBy`, or are these completely different roles?

**Comment by ibastrak** [comment]
Just got an answer from the custodians. It looks like they might be the same role (both naming places). However, the PlaceNamingAuthority has also a special function - registration/maintenance of official names

**Comment by dr-shorthair** [comment]
Just had a chat with Steve McEachern about this. I think I have it clear now - the Authority is the authorizing or gazetting body - it is a legal/institutional role. In many cases they are effectively ratifying a name that was assigned at some other level or by some other agent. But in Australia the legal role is formally exercised by the Jurisidictions. I will fix the ontology to reflect this.

**Comment by nicholascar** [comment]
The intention of the properties is as you have it: Authority is the gazetting body listing the Place Name in one of several defined Australian Gazetteers then there are other names assigned, perhaps alternate names, that are not so formal.
