### ISSUE TITLE
Place-name validity

### ISSUE THREAD

**Issue by dr-shorthair** [GeoscienceAustralia/Place-Names#21]
'Period of validity' is yet to be implemented. 
Does this inhere in 
- the name
- the association of the name with the place (i.e. feature)

That will seriously affect the complexity of the model. The latter would require an association class.

**Comment by ibastrak** [comment]
'period of validity' is linked to the name.

Question: understanding of geometry can change over time for the same place and name. Can it be resolved through prov?

**Comment by dr-shorthair** [comment]
@ibastrak @Shanecrossman here is a provisional model with two classes for place-names: 
- `PlaceName` is the basic one, which implicitly names a 'Point of Interest'. It has
  - optional `status` (missing &Implies; 'informal')
  - `wasNamedBy` is any agent
- `OfficialPlaceName` is the formal one, with
  - mandatory `status` with the value (`gazetted`|`released`|`published`|`retired`)
  - `wasNamedBy` must be an official `PlaceNamingAuthority` 
  - `Jurisdiction` is a specialization of `PlaceNamingAuthority` 
  - date properties for each stage of the lifecycle 
    - `dateGazetted` is mandatory, the others are optional

N.B. I have not yet worked up the name/language/pronunciation structure. 

![official-place-name](https://user-images.githubusercontent.com/608303/82640617-3cd20380-9c4e-11ea-9d20-1f6e326d53a5.png)

![classifiers](https://user-images.githubusercontent.com/608303/82640627-4196b780-9c4e-11ea-9fbf-a7cc7a9a84ec.png)

**Comment by bellie888** [comment]
Are we interested in including a AusPIX cell location for the position? This would be great for asking if there is a placename/s in a given AusPIX cell. This would be a simple lookup on the database - (but could do this on the fly as well - but is would be slower.)

Having AusPIX  is one way to data drill a location and return all the data for it. That is, "give me all the data for this cell" - returns meshblock, placenames, addresses, geofabric, CAPAD, economic activity etc etc.

Also if there are indigenous sites that are sensitive they can be located by a big AusPIX cell. That way the user would know there are indigenous sites in the locality without the exact location being given.

Alternatively, addresses could be described by a high res AusPIX cell for 'exact' location, but easily grouped into larger cells for density analysis or generalisation. Cheers

**Comment by dr-shorthair** [comment]
At the moment I would just encode that as an alternative Geometry, according to the model shown here: https://github.com/GeoscienceAustralia/AusPIX-DGGS-ontology/blob/master/auspix.md
```turtle

ex:Uluru
  rdf:type :Place ;
  :hasPlaceClassification <http://pid.geoscience.gov.au/def/voc/ga/PlaceType/MOUNTAIN> ;
  dcterms:identifier "NT_10532" ;
  geo:hasGeometry [
      rdf:type <http://linked.data.gov.au/def/auspix#Geometry> ;
      rdfs:member <http://ec2-52-63-73-113.ap-southeast-2.compute.amazonaws.com/AusPIX-DGGS-dataset/ausPIX/R7430551> ;
    ] ;
  geo:hasGeometry [
      rdf:type sf:Point ;
      geo:asWKT "POINT(-25.3415 131.0354)"^^geo:wktLiteral ;
    ] ;
.
```

**Comment by dr-shorthair** [comment]
@Shanecrossman @ibastrak see examples in the branch here: https://github.com/GeoscienceAustralia/Place-Names/blob/informal-names/placenames.ttl#L23
(Uluru - as discussed)

**Comment by dr-shorthair** [comment]
However, @nicholascar [has suggested](https://github.com/GeoscienceAustralia/AusPIX-DGGS-ontology/issues/1#issuecomment-633360244) perhaps a specific encoding for DGGS geometries. So maybe
```
ex:Uluru
  rdf:type :Place ;
  :hasPlaceClassification <http://pid.geoscience.gov.au/def/voc/ga/PlaceType/MOUNTAIN> ;
  dcterms:identifier "NT_10532" ;
  geo:hasGeometry [
     rdf:type geo:Geometry ;
     geox:asDGGS "R7430551"^^geox:dggsLiteral ;
    ] ;
  geo:hasGeometry [
      rdf:type sf:Point ;
      geo:asWKT "POINT(-25.3415 131.0354)"^^geo:wktLiteral ;
    ] ;
.
```

Then you need an engine that knows how to turn a list of DGGS cells into a useable geometry.

**Comment by bellie888** [comment]
@dr-shorthair @nicholascar 
We often make a visualisation of DGGS cells to include on GIS maps. In a sense this is "usable geometry".
Note though, representing spatial data as DGGS cells has a lossy component to it and the data will have a rasterised look to it. For example, a point that has been converted to a cell, that point could be anywhere in the cell (not just the centre). In a level 10 cell it could be anywhere in a 169 X 169 metre box.

To minimise this "lossy" component, we can use a higher resolution cell. In fact, the cell size could be  smaller that the accuracy of the original spatial data. 

An advantage of AusPIX is that the high resolution cells are always within their lower resolution parent. For example R574278 is somewhere inside R574

For any cell we can ask what the "useable geometry" is  - centroid, verticies etc
http://ec2-52-63-73-113.ap-southeast-2.compute.amazonaws.com/AusPIX-DGGS-dataset/ausPIX/S704884126

Cheers Joe

**Comment by dr-shorthair** [comment]
The 'lossiness' is implicit in `geox:asDGGS`.

**Comment by dr-shorthair** [comment]
(not really 'lossiness' - rather just fixed precision.)

**Comment by bellie888** [comment]
Yep, true
Here is an example of a DGGS'ed stream.

![streamDGGS](https://user-images.githubusercontent.com/23160509/82781143-6aac8780-9e9c-11ea-88fa-825da1d119f1.jpg)

**Comment by nicholascar** [comment]
So this is why I think using literals for the DGGS data is a good idea: the structure of the numbers - R574278 being within R574 - means that secondary systems processing literals like that will be fast.

**Comment by dr-shorthair** [comment]
@bellie888 the idea is that the `dggsLiteral` would take a list of Cell IDs. e.g. 
```
ex:XX_10532
  rdf:type :Place ;
  :hasPlaceClassification <http://pid.geoscience.gov.au/def/voc/ga/PlaceType/WATERCOURSE> ;
  dcterms:identifier "XX_10532" ;
  geo:hasGeometry [
     rdf:type geo:Geometry ;
     geox:asDGGS "R7430550 R7430551 R7430552 ... "^^geox:dggsLiteral ;
    ] ;
  geo:hasGeometry [
      rdf:type sf:LineString ;
      geo:asWKT "LINESTRING(-25.3415 131.0354 , ... )"^^geo:wktLiteral ;
    ] ;
.
```

**Comment by bellie888** [comment]
nice, is there a limit?

**Comment by dr-shorthair** [comment]
We are making this up, so there is only a limit if you want one.

**Comment by dr-shorthair** [comment]
This discussion really belongs over in the GEOX repo - I've copied it to https://github.com/CSIRO-enviro-informatics/geosparql-ext-ont/issues/7#issuecomment-633398527 and deleted it here so we don't confuse what is under discussion in _this_ issue

**Comment by ibastrak** [comment]
Hi Simon, 
Question about position of 'status' element: 
At the moment it's part of OfficialPlaceName. This subclass has two mandatory elements: status and wasNamedBy. Depending on the vocabulary values associated with wasNamedBy the 'status' may or may not be part of this subclass. 
If the status of the place name is 'informal', the associated authority may not be known. Therefore, if the wasNamedBy allows 'unknown' as one of the authority values then  the combination of 'informal' status with 'unknown' wasNamedBy would be valid for the proposed subclass. If we want to keep the wasNamedBy  associated only with known official authorities then status would need to be moved to the PlaceName class or allowed to be [0..1]

**Comment by dr-shorthair** [comment]
My suggestion is that informal names be instances of the super-class `PlaceName`. `status` is optional there. Compare 
```turtle
ex:Ayers-Rock-Uluru
  a :OfficialPlaceName ;
  loci:isMemberOf <https://www.ntlis.nt.gov.au/placenames/> ;
  :dateGazetted "1990-01-01"^^xsd:date ;
  :dateRetired "2005-12-31"^^xsd:date ;
  :name "Ayers Rock (Uluru)" ;
  :placeNameOf ex:NT_10532 ;
  :status :retired ;
  :wasNamedBy <https://www.ntlis.nt.gov.au/placenames/> ;
  rdfs:comment "NOTE: EXAMPLE ONLY DETAILS MAY BE INCORRECT" ;
  rdfs:label "Ayers Rock (Uluru)" ;
.
```
and
```turtle
ex:DH
  a :PlaceName ;
  loci:isMemberOf <https://www.ntlis.nt.gov.au/placenames/> ;
  :name "My dolls house" ;
  :placeNameOf ex:vic-987 ;
  :status :informal ;
  :wasNamedBy :unknown ;
.
```

**Comment by ibastrak** [comment]
Maybe it's my lack of understanding - I cannot quite understand how status can be changed to optional in the PlaceName class but remain mandatory in the subclass. Would the general class inherit multiplicity assigned to the elements in the subclass?

**Comment by dr-shorthair** [comment]
Placename is the _superset_, not the sub-class. You must be reading the arrow wrong. 

But 'inheritance' is the wrong way to think about it. These classes are more like 'sets'. Individual members of the subset (i.e. official placenames) are all members of the superset (i.e. placenames), but members of the subset (i.e. official placenames) have additional restrictions and restrictions. 

The `rdfs:domain` of `status` is not specified, so it is optional anywhere (Open World Assumption).

**Comment by ibastrak** [comment]
I meant that PlaceNames was a superset with OfficialPlaceName as one of PlaceName 'types' containing additional elements specific for official placenames.

What I didn't know was that status could be used anywhere as an optional element without being listed as an element in a class - the diagram above.
