### ISSUE TITLE
Formalize the Place Name Formality classification vocabulary

### ISSUE THREAD

**Issue by dr-shorthair** [GeoscienceAustralia/Place-Names#23]
Currently there are just three members which are embedded in the ontology rather than managed externally
- Historical
- Informal
- Official

Is this all that's required?

**Comment by ibastrak** [comment]
Can you remind me how their indigenous background is defined now?

It might be in a different attribute.

**Comment by dr-shorthair** [comment]
I'm working from the following:
1. the prototype API at http://ec2-52-63-73-113.ap-southeast-2.compute.amazonaws.com/placenames-dataset/placename/ 
2. the prototype ontology, at https://raw.githack.com/GeoscienceAustralia/Place-Names/master/placenames.html

Note that I've simplified the ontology already, relative the original that Irina and Armin developed, primarily to align with Loc-I according to http://loci.cat/loci-datasets.html I started from the version in September. However, I haven't thrown anything away, just moved things around a bit. There are three code-lists or controlled vocabularies implied:
1. place-type
2. name-formality
3. name-status

These should probably all be managed external to the ontology. The Ontology should probably just have `skos:Concept` as the range of each of the properties, and then the actual vocabularies can be pulled in through a SHACL constraint rather than the OWL ontology.

**Comment by dr-shorthair** [comment]
There was nothing about indigenous background in the material I started from.

**Comment by ibastrak** [comment]
Oh, ok. At some stage it was a conversation about having indication of ‘ethnic’ origin of the name as a sub-classification as the adopted name can be both formal and informal.

**Comment by dr-shorthair** [comment]
Proposed to manage this with a consolidated Status vocabulary, and a PlaceName/OfficialPlacename split - see https://github.com/GeoscienceAustralia/Place-Names/issues/21#issuecomment-632523449

**Comment by ibastrak** [comment]
Simon,
In our placename discussion last Friday you mentioned two ways to populate hierarchical vocabularies. Can you send examples of how the difference should look like please?
We are about to undertake a massive work on geography related vocabularies and planning to put a couple of the on RVA.

**Comment by dr-shorthair** [comment]
Lets move that discussion here: https://github.com/GeoscienceAustralia/Place-Names/issues/22 (but I can't look at it today, sorry)

**Comment by ibastrak** [comment]
good, thanks.

**Comment by dr-shorthair** [comment]
Resolved with https://github.com/GeoscienceAustralia/Place-Names/pull/26
