### ISSUE TITLE
Review Place-Names ontology 

### ISSUE THREAD

**Issue by dr-shorthair** [GeoscienceAustralia/Place-Names#25]
GA to review http://linked.data.gov.au/def/placenames to verify that all requirements are satisfied. 
In particular, allowing for alternative and indigenous names.

**Comment by dr-shorthair** [comment]
@ibastrak  wrote:

Shane and I discussed the Place Name characteristics.

Based on this discussion, we think that attributes of the Place Name class need to be reviewed.

The Place Name can be official/non-official and historic/current and indigenous/non-indigenous as the same time. I think at the moment the Place Name class has no reference to the origin of the name. Also, there is no separation between official status and historic nature of the name.

e.g. Narrabundah (suburb in Canberra) is official, current and indigenous in the origin of its name
e.g. 'New Holland' or 'Terra Australis' are official, historic and non-indigenous names of Australia
e.g. 'Van Diemen's Land' is an official, historic and non-indigenous names of Tasmania.

One of issues is probably not for the current model but for investigating in the future is linkages between indigenous and non-indigenous names related to the same place or combination of places that may have different geometries.

**Comment by dr-shorthair** [comment]
@ibastrak wrote:
> I think at the moment the Place Name class has no reference to the origin of the name.

The property [:wasNamedBy](http://linked.data.gov.au/def/placenames#wasnamedby) refers to _The Agent (person, community, organization) that assigned the name to the Place_ which indicates its origin. Note that this is a sub-property of `prov:wasAttributedTo`. 

If you need more detail about the place-naming event or activity, then we should use `prov:wasGeneratedBy` and build a `prov:Activity` to describe this.

**Comment by dr-shorthair** [comment]
@ibastrak wrote: 
>  there is no separation between official status and historic nature of the name.

There are three relevant attributes related to this: 

- [:hasPlaceNamingAuthority](http://linked.data.gov.au/def/placenames#hasPlaceNamingAuthority) points to the authority for the name, a Jurisdiction, denoted by a URIreference that should point to some controlled list of naming-authorities. This attribute is 'mandatory' since I think it was intended to reflect the governance process for the gazetteer. Maybe _Jurisidiction_ is too narrow? 

- [:status](http://linked.data.gov.au/def/placenames#hasstatus) refers to the status within the register (i.e. the gazetteer) with the value taken from a codelist of terms that are primarily about lifecycle - see https://github.com/GeoscienceAustralia/Place-Names/blob/master/placenames.ttl#L447 

- [:hasPlaceNameFormality](http://linked.data.gov.au/def/placenames#hasPlaceNameFormality) takes a value from a different codelist. The provisional entries are `Historical`, `Informal`, `Official` but there is a lot of scope for refining this vocabulary - see https://github.com/GeoscienceAustralia/Place-Names/blob/master/placenames.ttl#L421 

The codelists are provisional, but might be controlled by ICSM or ANZLIC or Lara or something.

**Comment by ibastrak** [comment]
1. By origin of the name I meant its indigenous nature. The Agent represents an entity that named the place. The indigenous origin may be only assumed from that. Having an attribute separating indigenous vs non-indigenous will remove uncertainty. Maybe we need to look into prov:Activity
2. :hasPlaceNameFormality - I think we need to look into that and talk to the ICSM PlaceNames Working Group that manages this vocabulary. We may ask Nick to talk to Susan (Chair of ICSM PlaceNames WG) about it (both on Brisbane). Every PlaceNames vocabulary we published is governed by the ICSM PlaceNames WG. They are quite new yo this world and all have mapping/GIS background. Many entries in vocabularies were already improved through previous interactions.

**Comment by dr-shorthair** [comment]
1. It is easy to add attributes or flags. But if there are existing slots that might make sense then I prefer to look at those first. For example, the string-literal that is the value of the `:name` property can have an RDF Language Tag associated - see https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal . e.g.
```turtle
<> :name "Florence"@en ;
    :name "Firenze"@it .
```
However, the [IANA registry of language subtags](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) does not mention Australian Aboriginal languages so this may not work in the short term :-( 

But note the approach I'm using here: use an existing slot in the schema if possible, and improve the codeList if necessary.

**Comment by ibastrak** [comment]
I talked to Shane about it today to clarify a couple of things. It should be quite easy to modify both database structure by adding a couple attributes or improve vocabularies if needed.

There is a keen interest in Victoria and QLD in particular to be able to record whether the name is indigenous. There might be other states as well.

The extension that I mentioned in one of the comments was about seen how the Placenames ontology could be links to some sort  of indigenous ontology. Is my understanding right that you've done some work with Steve (ANU) on around this topic? Can it be re-used? Can it cover entities as language there.

My preference is to keep Place Names simple as possible and link to other things when necessary.

**Comment by ibastrak** [comment]
When do you have time to 'get together' to look at the existing attributes?

**Comment by dr-shorthair** [comment]
However, [ISO 639-2](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes#A) does include `aus` for Australian (i.e. aboriginal) languages. But there would need to be subtags for the dialect and the orthography - https://tools.ietf.org/html/bcp47#section-2.1

**Comment by dr-shorthair** [comment]
>  Is my understanding right that you've done some work with Steve (ANU) on around this topic? 

No. Occasional talk with a colleague in CSIRO, but no progress.

**Comment by ibastrak** [comment]
Thanks, Similar here. I had several conversations with people from ANU but without progress.
Time is the issue to pursue for us. However, Shane and I are still trying to find time to connect to this community.

Back to the language attribute comments:
There are two ways from my perspective to indicate indigenous nature: directly (without specifying what language it is), just saying this is 'indigenous' name or indirectly by saying this is 'xxx' language and to rely on the 'language' ontology/ISO 639-2 to extract its subtag.
I am not sure that the Placename data holding and processes for its data collection in the Gov departments of States/Territories are mature enough to be able to specify a particular language. I need to talk to Shane about it. The structure and data aggregation processes for the Placenames dataset we use are currently controlled by GA and agreed by States. We might be able to partially resolve the issue of specifying language by connecting to the research community data - this needs to be tested.

**Comment by dr-shorthair** [comment]
If an 'indigenous' flag is a key aspect of Australian place names, then it probably merits a specific flag. I'll add it.

**Comment by dr-shorthair** [comment]
Get together time: I'm free tomorrow (Friday).

**Comment by ibastrak** [comment]
I am pretty flexible tomorrow except for 10 - 11 meeting. Any preferred time from you?

**Comment by dr-shorthair** [comment]
Indigenous flag added
Support for informal names clarified
Lifecycle dates formalized

Resolved in https://github.com/GeoscienceAustralia/Place-Names/pull/26
See http://linked.data.gov.au/def/placenames
